; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = mhetesp32devkit
framework = arduino
monitor_speed = 115200

[env:blink]
build_src_filter= -<*> +<blink.cpp>

[env:serial]
build_src_filter = -<*> +<serial.cpp>

[env:fade]
build_src_filter = -<*> +<fade.cpp>

[env:millis]
build_src_filter = -<*> +<millis.cpp>

[env:button]
build_src_filter = -<*> +<button.cpp>

[env:wifi]
build_src_filter = -<*> +<wifi.cpp>

[env:scan]
build_src_filter = -<*> +<scan.cpp>

[env:fetch]
build_src_filter = -<*> +<fetch.cpp>

